name = "mob-games"
author = "leafd, thomas"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48b8ead9d77c2a80ffb5609ceaf241e0ff794736286104d13137ef7a93497fef"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
