name = "mob-games"
author = "leafd, thomas"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce38d4a2d4f4a23eee77b46548f6723c712e4998190811d254ae59c24231b279"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
